"""Initial migration

Revision ID: 20b557b4ee7e
Revises: 
Create Date: 2026-02-13 23:41:46.302420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b557b4ee7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('has_website', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'has_website')
    op.drop_column('leads', 'phone')
    # ### end Alembic commands ###
